name: ci-cd

on: [push, pull_request]

jobs:
  ci:
    # Set up operating system
    runs-on: ubuntu-latest

    # Define job steps
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Install poetry
        uses: snok/install-poetry@v1

      - name: Install package
        run: poetry install

      - name: Test with pytest
        run: poetry run pytest tests/ --cov=google_nest_camera_proxy --cov-report=xml

      - name: Use Codecov to track and report on coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml

      - name: Build documentation
        run: poetry run make html --directory docs/

  cd:
    # Only run this job if the "ci" job passes
    needs: ci

    concurrency: release
    permissions:
      id-token: write
      contents: write

    # Only run this job if new work is pushed to "main"
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    # Set up operating system
    runs-on: ubuntu-latest

    # Define job steps
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Check-out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: xevg/google-nest-camera-proxy
          token: ${{ secrets.MY_TOKEN }}

      - name: Install poetry
        uses: snok/install-poetry@v1

      - name: Install package
        run: poetry install

      - name: Python Semantic Release
        uses: python-semantic-release/python-semantic-release@master
        with:
          github_token:
            ${{ secrets.GITHUB_TOKEN }}

      - name: Poetry Build
        run: poetry build

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository_url: https://test.pypi.org/legacy/

      - name: Test install from TestPyPI
        run: |
           pip install \
           --index-url https://test.pypi.org/simple/ \
           --extra-index-url https://pypi.org/simple \
           google_nest_camera_proxy


      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      #- name: Use Python Semantic Release to prepare release
      #  env:
      #    # This token is created automatically by GH Actions
      #    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  run: |
      #      git config user.name github-actions
      #      git config user.email github-actions@github.com
      #      poetry run semantic-release publish

      # - name: Poetry Build
      #  run: poetry build